


const DEFAULT_CONFIG = window.NILAMCHAT_CONFIG || {supabaseUrl:'',supabaseAnonKey:''};
let sb=null, user=null, profile=null, active=null, channel=null, globalChannel=null, presence=null, conversations=[], allPeople=[], profilesCache=new Map(), booting=false, bootedUserId=null;
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const initials=n=>(n||'?').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();
const fmt=d=>d?new Intl.DateTimeFormat([], {hour:'2-digit',minute:'2-digit'}).format(new Date(d)):'';
const ago=d=>{if(!d)return '';const x=(Date.now()-new Date(d).getTime())/1000;if(x<60)return 'now';if(x<3600)return Math.floor(x/60)+'m';if(x<86400)return Math.floor(x/3600)+'h';return Math.floor(x/86400)+'d'};
function avatar(p,cls='avatar'){return `<div class="${cls}">${p?.avatar_url?`<img src="${esc(p.avatar_url)}" alt="">`:esc(initials(p?.display_name||p?.username))}</div>`}
function render(){ if(!DEFAULT_CONFIG.supabaseUrl||!DEFAULT_CONFIG.supabaseAnonKey){renderSetup();return} if(!sb){sb=supabase.createClient(DEFAULT_CONFIG.supabaseUrl,DEFAULT_CONFIG.supabaseAnonKey); sb.auth.onAuthStateChange((_e,s)=>{user=s?.user||null;if(user) boot();else {cleanupRealtime();renderAuth('login')}}); sb.auth.getSession().then(({data})=>{user=data.session?.user||null; user?boot():renderAuth('login')});return} user?boot():renderAuth('login') }
function renderSetup(){document.body.innerHTML=`<div id="app"><div class="setup"><div class="logo">💬</div><h2>Connect NilamChat</h2><p class="muted">Add your Supabase Project URL and anon/publishable key in <code>config.js</code>, then upload this folder to Netlify.</p><div class="field"><label>Supabase Project URL</label><input id="cfgurl" placeholder="https://xxxxx.supabase.co"></div><div class="field"><label>Supabase anon/public key</label><input id="cfgkey" placeholder="eyJ..."></div><button class="primary" onclick="saveConfig()">Connect & Continue</button><p><small>Use only the public anon/publishable key. Never put your Supabase service-role key in this website.</small></p></div></div>`}
function saveConfig(){const u=$('#cfgurl').value.trim(),k=$('#cfgkey').value.trim();if(!u||!k)return alert('Enter both Supabase values.');localStorage.setItem('nilamchat_config',JSON.stringify({supabaseUrl:u,supabaseAnonKey:k}));location.reload()}
function config(){try{return JSON.parse(localStorage.getItem('nilamchat_config'))||DEFAULT_CONFIG}catch{return DEFAULT_CONFIG}}
function renderAuth(mode='login',msg=''){const isLogin=mode==='login'; document.body.innerHTML=`<div id="app"><div class="auth"><div class="logo" style="margin-bottom:18px">💬</div><h1>${isLogin?'Welcome back':'Create account'}</h1><p>${isLogin?'Sign in to continue your conversations.':'Join NilamChat and start chatting in real time.'}</p>${msg?`<div class="${msg.ok?'success':'error'}">${esc(msg.text)}</div>`:''}${!isLogin?`<div class="field"><label>Username</label><input id="username" autocomplete="username" placeholder="yourname"></div>`:''}<div class="field"><label>Email</label><input id="email" type="email" autocomplete="email" placeholder="you@example.com"></div><div class="field"><label>Password</label><input id="password" type="password" autocomplete="current-password" placeholder="••••••••"></div><button class="primary" onclick="${isLogin?'doLogin()':'doRegister()'}">${isLogin?'Sign in':'Create account'}</button>${isLogin?`<div style="text-align:center;margin-top:16px"><button class="linkbtn" onclick="forgot()">Forgot password?</button></div>`:''}<div class="authfooter">${isLogin?'New here?':'Already have an account?'} <button class="linkbtn" onclick="renderAuth('${isLogin?'register':'login'}')">${isLogin?'Create account':'Sign in'}</button></div></div></div>`}
async function doLogin(){try{const email=$('#email').value.trim(),password=$('#password').value;const {error}=await sb.auth.signInWithPassword({email,password});if(error)throw error}catch(e){renderAuth('login',{text:e.message})}}
async function doRegister(){try{const username=$('#username').value.trim(),email=$('#email').value.trim(),password=$('#password').value;if(username.length<3)throw Error('Username must be at least 3 characters.');const {data,error}=await sb.auth.signUp({email,password,data:{username}});if(error)throw error;if(!data.session)renderAuth('login',{ok:true,text:'Account created. Check your email to confirm, then sign in.'})}catch(e){renderAuth('register',{text:e.message})}}
async function forgot(){const email=prompt('Enter your email address:');if(!email)return;const {error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:location.origin});alert(error?error.message:'Password reset email sent.')}
async function boot(){if(!user)return;if(booting)return;if(bootedUserId===user.id && document.querySelector('.shell'))return;booting=true;try{if(bootedUserId!==user.id){cleanupRealtime();bootedUserId=user.id}const {data}=await sb.from('profiles').select('*').eq('id',user.id).maybeSingle();profile=data||{id:user.id,username:user.email?.split('@')[0],display_name:user.email?.split('@')[0]};renderShell();await loadConversations();subscribeGlobal();setOnline(true)}catch(e){renderAuth('login',{text:e.message});bootedUserId=null}finally{booting=false}}
function renderShell(){document.body.innerHTML=`<div id="app"><div class="shell" id="shell"><aside class="sidebar"><div class="topbar"><div class="brand"><div class="logo">💬</div>NilamChat</div><div><button class="iconbtn" title="New chat" onclick="showSearch()">＋</button><button class="iconbtn" title="Profile" onclick="showProfile()">⋮</button></div></div><div class="search"><div class="searchbox">⌕<input id="search" placeholder="Search people" oninput="filterChats(this.value)"></div></div><div class="chatlist" id="chatlist"></div></aside><main class="main" id="main"><div class="empty"><div class="emptybox"><div class="biglogo">💬</div><h2>NilamChat</h2><p class="muted">Select a conversation or start a new chat. Messages update in real time.</p><button class="primary" style="max-width:220px" onclick="showSearch()">Start a new chat</button></div></div></main></div></div><div id="drawer"></div>`}
async function loadConversations(){
  const {data,error}=await sb.from('conversation_overview').select('*').order('last_message_at',{ascending:false});
  if(error)throw error;
  // Keep only one conversation row per other user. This also protects the UI
  // if old/duplicate 1-to-1 conversation records exist in the database.
  const seen=new Set();
  conversations=(data||[]).filter(c=>{if(seen.has(c.other_user_id))return false;seen.add(c.other_user_id);return c.other_user_id!==user.id});
  await loadPeople();
  renderChats();
}
async function loadPeople(){
  const {data,error}=await sb.from('profiles').select('id,username,display_name,avatar_url,is_online,last_seen').neq('id',user.id).order('display_name');
  if(error)throw error;
  allPeople=data||[];
}
function renderChats(list=conversations){
  const el=$('#chatlist');
  const q=($('#search')?.value||'').trim().toLowerCase();
  const people=(allPeople||[]).filter(p=>(p.display_name||p.username||'').toLowerCase().includes(q));
  const byOther=new Map(conversations.map(c=>[c.other_user_id,c]));
  if(!people.length){el.innerHTML=`<div style="padding:40px 20px;text-align:center" class="muted">No other users found.</div>`;return}
  el.innerHTML=people.map(p=>{
    const c=byOther.get(p.id);
    const name=p.display_name||p.username;
    const preview=c?.last_message_content||'Start chatting';
    return `<button class="chatitem ${active?.other_user_id===p.id?'active':''}" style="width:100%;text-align:left;background:none;color:inherit" onclick="${c?`openChat('${c.conversation_id}','${p.id}')`:`startChat('${p.id}')`}">${avatar(p)}<div class="chatmeta"><div class="row"><span class="name">${esc(name)}</span><span class="time">${c?ago(c.last_message_at):(p.is_online?'online':'')}</span></div><div class="row"><span class="preview">${esc(preview)}</span>${c?.unread_count?`<span class="badge">${c.unread_count}</span>`:''}</div></div></button>`
  }).join('');
}
function filterChats(q){renderChats()}
async function showSearch(){const {data}=await sb.from('profiles').select('*').neq('id',user.id).order('display_name').limit(100);const rows=data||[];openDrawer(`<div class="drawerhead"><h2>New chat</h2><button class="iconbtn" onclick="closeDrawer()">×</button></div><div class="searchbox" style="margin:15px 0">⌕<input id="userq" placeholder="Search people" oninput="filterPeople()"></div><div id="people">${peopleHtml(rows)}</div>`,{people:rows})}
let peopleCache=[];function peopleHtml(rows){peopleCache=rows;return rows.length?rows.map(p=>`<button class="chatitem" style="width:100%;text-align:left;background:none;color:inherit" onclick="startChat('${p.id}')">${avatar(p)}<div class="chatmeta"><div class="name">${esc(p.display_name||p.username)}</div><div class="preview">@${esc(p.username)}</div></div></button>`).join(''):`<div class="muted" style="padding:25px">No users found.</div>`}
function filterPeople(){const q=$('#userq').value.toLowerCase();$('#people').innerHTML=peopleHtml(peopleCache.filter(p=>(p.display_name||p.username||'').toLowerCase().includes(q)))}
async function startChat(other){if(other===user.id)return;closeDrawer();const {data,error}=await sb.rpc('get_or_create_conversation',{other_user_id:other});if(error)return alert(error.message);await loadConversations();openChat(data,other)}
async function openChat(cid,otherId){const c=conversations.find(x=>x.conversation_id===cid);active={conversation_id:cid,other_user_id:otherId,profile:{display_name:c?.other_display_name,username:c?.other_username,avatar_url:c?.other_avatar_url,is_online:c?.other_is_online}};renderChatHead();await loadMessages(cid);subscribeChat(cid);await sb.rpc('mark_conversation_read',{p_conversation_id:cid});await loadConversations();$('#shell').classList.add('chat-open')}
function renderChatHead(){const p=active.profile;$('#main').innerHTML=`<div class="chathead"><button class="iconbtn mobileonly" onclick="closeChat()">‹</button>${avatar(p)}<div class="headinfo"><div class="name">${esc(p.display_name||p.username)}</div><div class="online">${p.is_online?'online':'offline'}</div></div><button class="iconbtn" onclick="showUser('${active.other_user_id}')">⋮</button></div><div class="messages" id="messages"></div><div class="composer"><textarea id="composer" rows="1" placeholder="Type a message" onkeydown="composerKey(event)"></textarea><button class="send" id="send" onclick="sendMessage()">➤</button></div>`}
async function loadMessages(cid){const {data,error}=await sb.from('messages').select('*').eq('conversation_id',cid).order('created_at',{ascending:true}).limit(100);if(error)return alert(error.message);$('#messages').innerHTML=(data||[]).map(messageHtml).join('');scrollBottom()}
function messageHtml(m){const mine=m.sender_id===user.id;return `<div class="msgrow ${mine?'mine':''}"><div class="bubble"><div class="msgtext">${esc(m.content||'')}</div><div class="msgtime">${fmt(m.created_at)} ${mine?'✓✓':''}</div></div></div>`}
function scrollBottom(){const e=$('#messages');if(e)e.scrollTop=e.scrollHeight}
async function sendMessage(){const input=$('#composer'),content=input.value.trim();if(!content||!active)return;input.value='';$('#send').disabled=true;const {error}=await sb.from('messages').insert({conversation_id:active.conversation_id,sender_id:user.id,content,message_type:'text'});$('#send').disabled=false;if(error){input.value=content;alert(error.message)}}
function composerKey(e){if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMessage()}}
function subscribeChat(cid){if(channel)sb.removeChannel(channel);channel=sb.channel('web-chat-'+cid).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:`conversation_id=eq.${cid}`},p=>{$('#messages')?.insertAdjacentHTML('beforeend',messageHtml(p.new));scrollBottom();if(p.new.sender_id!==user.id)sb.rpc('mark_conversation_read',{p_conversation_id:cid})}).subscribe()}
function subscribeGlobal(){if(globalChannel||!user)return;globalChannel=sb.channel('web-global').on('postgres_changes',{event:'INSERT',schema:'public',table:'messages'},async()=>{await loadConversations()}).on('postgres_changes',{event:'UPDATE',schema:'public',table:'profiles'},async p=>{if(p.new.id===user.id)profile=p.new;await loadConversations()}).subscribe();if(!presence){presence=sb.channel('web-presence',{config:{presence:{key:user.id}}}).on('presence',{event:'sync'},()=>{}).subscribe(async status=>{if(status==='SUBSCRIBED')await presence.track({user_id:user.id})})}}
function cleanupRealtime(){if(!sb)return;if(channel){sb.removeChannel(channel);channel=null}if(globalChannel){sb.removeChannel(globalChannel);globalChannel=null}if(presence){sb.removeChannel(presence);presence=null}active=null;bootedUserId=null}
async function setOnline(v){try{await sb.from('profiles').update({is_online:v,last_seen:new Date().toISOString()}).eq('id',user.id)}catch(e){}}
function closeChat(){$('#shell').classList.remove('chat-open');if(channel){sb.removeChannel(channel);channel=null}}
function showProfile(){openDrawer(`<div class="drawerhead"><h2>Profile</h2><button class="iconbtn" onclick="closeDrawer()">×</button></div><div class="profilehero">${avatar(profile)}<h2>${esc(profile.display_name||profile.username)}</h2><div class="muted">@${esc(profile.username)}</div><p class="muted">${esc(profile.about||'Hey there! I am using NilamChat.')}</p></div><div class="setting"><b>Account</b><br><button onclick="editProfile()">Edit profile</button></div><div class="setting"><b>Theme</b><br><button onclick="toggleTheme()">Toggle dark/light</button></div><div class="setting"><button class="logout" onclick="doLogout()">Log out</button></div>`)}
async function editProfile(){openDrawer(`<div class="drawerhead"><h2>Edit profile</h2><button class="iconbtn" onclick="showProfile()">×</button></div><div class="field"><label>Display name</label><input id="edname" value="${esc(profile.display_name||'')}"></div><div class="field"><label>About</label><input id="edabout" value="${esc(profile.about||'')}"></div><button class="primary" onclick="saveProfile()">Save changes</button>`)}
async function saveProfile(){const {error}=await sb.from('profiles').update({display_name:$('#edname').value.trim(),about:$('#edabout').value.trim()}).eq('id',user.id);if(error)return alert(error.message);const {data}=await sb.from('profiles').select('*').eq('id',user.id).single();profile=data;showProfile();loadConversations()}
async function showUser(id){const {data}=await sb.from('profiles').select('*').eq('id',id).single();if(!data)return;openDrawer(`<div class="drawerhead"><h2>Contact</h2><button class="iconbtn" onclick="closeDrawer()">×</button></div><div class="profilehero">${avatar(data)}<h2>${esc(data.display_name||data.username)}</h2><div class="muted">@${esc(data.username)}</div><p class="muted">${esc(data.about||'')}</p><div class="online">${data.is_online?'● Online':'Last seen '+ago(data.last_seen)}</div></div><div class="setting"><b>Chat</b><br><button class="dangerbtn" onclick="confirmDeleteChat()">🗑 Delete chat</button><div class="muted" style="font-size:12px;margin-top:8px">Removes this chat from your chat list. It does not delete the other person's copy.</div></div>`)}
async function confirmDeleteChat(){if(!active?.conversation_id)return;const name=active.profile?.display_name||active.profile?.username||'this chat';if(!confirm(`Delete chat with ${name}?\n\nThis removes the conversation from your chat list. Your contact will keep their copy.`))return;const cid=active.conversation_id;const {error}=await sb.rpc('delete_conversation_for_user',{p_conversation_id:cid});if(error){alert('Could not delete chat: '+error.message);return}closeDrawer();if(channel){sb.removeChannel(channel);channel=null}active=null;$('#shell').classList.remove('chat-open');$('#main').innerHTML='<div class="empty"><div class="emptybox"><div class="biglogo">💬</div><h2>NilamChat</h2><p class="muted">Select a conversation or start a new chat. Messages update in real time.</p><button class="primary" style="max-width:220px" onclick="showSearch()">Start a new chat</button></div></div>';await loadConversations();}
function openDrawer(html){$('#drawer').innerHTML=`<div class="drawer" onclick="if(event.target===this)closeDrawer()"><div class="drawerbox">${html}</div></div>`}function closeDrawer(){$('#drawer').innerHTML=''}
function toggleTheme(){document.documentElement.dataset.light=document.documentElement.dataset.light==='1'?'':'1';if(document.documentElement.dataset.light==='1'){document.documentElement.style.setProperty('--bg','#f2f5f7');document.documentElement.style.setProperty('--panel','#fff');document.documentElement.style.setProperty('--panel2','#e8eef1');document.documentElement.style.setProperty('--text','#15232b');document.documentElement.style.setProperty('--muted','#667781');document.documentElement.style.setProperty('--bubble','#fff');document.documentElement.style.setProperty('--mine','#d9fdd3')}else location.reload()}
async function doLogout(){await setOnline(false);cleanupRealtime();await sb.auth.signOut();closeDrawer()}
const saved=config();if(saved.supabaseUrl&&saved.supabaseAnonKey){DEFAULT_CONFIG.supabaseUrl=saved.supabaseUrl;DEFAULT_CONFIG.supabaseAnonKey=saved.supabaseAnonKey}render();
window.addEventListener('beforeunload',()=>{if(user)setOnline(false)});
